### PR TITLE
Extend DomainSidPlugin to extract the domain name as well

### PR DESCRIPTION
**Pull request by ravenexp**
Do not fail when the machine in not in an AD domain.
Report the workgroup name as the domain name instead.

Add a basic plugin unit test using a clean SECURITY hive data file.

### CODE REVIEW

**Review by tincho9 — CHANGES_REQUESTED** [review]
Why did you modify the SYSTEM hive files in `regipy_tests/data`?

**Comment by ravenexp** [comment]
I did not modify them, but only cleared the executable permission bits (`chmod -x`).
It is also reflected in the commit message.

The GitHub interface does not make it obvious, but one can see that the contents of these files is not changed because the diff size is 0.

I can revert this and resubmit, if you want to leave them as is.

**Comment by tincho9** [comment]
> I did not modify them, but only cleared the executable permission bits (`chmod -x`).
> It is also reflected in the commit message.
> 
> The GitHub interface does not make it obvious, but one can see that the contents of these files is not changed because the diff size is 0.
> 
> I can revert this and resubmit, if you want to leave them as is.

No, it's totally fine. Fix the conflict and I'll merge and create a release.

**Comment by ravenexp** [comment]
I've rebased on master and fixed the conflict.

**Pull request merged**
