### PR TITLE
Typed Paths Artifact

### PR DESCRIPTION
**Pull request by andreisss**
This key shows what you have manually typed a path into the Start menu or into the Explorer bar. The values are not written to the key until the Explorer window is closed.

### CODE REVIEW

**Comment by mkorman90** [comment]
I really appreciate your contribution! Can you add a test, possibly based on one of the existing hive files? Let me know if you need help :)

**Comment by andreisss** [comment]
> I really appreciate your contribution! Can you add a test, possibly based on one of the existing hive files? Let me know if you need help :)

Hi,

Yes, you can see this test with your file: **NTUSER_BAGMRU.DAT**
test_1

This is the output generated from the file.

{
    "typed_paths": {
        "last_write": "2022-02-06T13:46:04.945080+00:00",
        "entries": [
            {
                "url1": "cmd"
            },
            {
                "url2": "C:\\Offline\\AD"
            },
            {
                "url3": "git"
            },
            {
                "url4": "powershell"
            },
            {
                "url5": "C:\\Program Files"
            },
            {
                "url6": "Network"
            },
            {
                "url7": "\\\\wsl$\\Ubuntu\\projects\\CAD316_001\\partition_p1"
            },
            {
                "url8": "\\\\wsl$\\Ubuntu\\projects"
            },
            {
                "url9": "\\\\wsl$\\Ubuntu"
            },
            {
                "url10": "C:\\Users\\tony\\Github"
            },
            {
                "url11": "C:\\Users\\tony\\Github\\velocity-client-master"
            },
            {
                "url12": "C:\\Users\\tony\\Github\\cogz"
            },
            {
                "url13": "C:\\Users\\tony\\Github\\cogz\\cogz"
            },
            {
                "url14": "Quick access"
            },
            {
                "url15": "C:\\ProgramData\\chocolatey\\lib\\yara\\tools"
            },
            {
                "url16": "C:\\Training\\MT01\\exercise"
            }
        ]
    }
}

**Comment by mkorman90** [comment]
> > I really appreciate your contribution! Can you add a test, possibly based on one of the existing hive files? Let me know if you need help :)
> 
> Hi,
> 
> Yes, you can see this test with your file: **NTUSER_BAGMRU.DAT** test_1
> 
> This is the output generated from the file.
> 
> { "typed_paths": { "last_write": "2022-02-06T13:46:04.945080+00:00", "entries": [ { "url1": "cmd" }, { "url2": "C:\Offline\AD" }, { "url3": "git" }, { "url4": "powershell" }, { "url5": "C:\Program Files" }, { "url6": "Network" }, { "url7": "\\wsl$\Ubuntu\projects\CAD316_001\partition_p1" }, { "url8": "\\wsl$\Ubuntu\projects" }, { "url9": "\\wsl$\Ubuntu" }, { "url10": "C:\Users\tony\Github" }, { "url11": "C:\Users\tony\Github\velocity-client-master" }, { "url12": "C:\Users\tony\Github\cogz" }, { "url13": "C:\Users\tony\Github\cogz\cogz" }, { "url14": "Quick access" }, { "url15": "C:\ProgramData\chocolatey\lib\yara\tools" }, { "url16": "C:\Training\MT01\exercise" } ] } }

Looks great! Can you add this as a test? Here is an [example](https://github.com/mkorman90/regipy/blob/master/regipy_tests/plugin_tests.py#L733).

**Review by mkorman90 — CHANGES_REQUESTED** [review]
Looks great! Can you add this as a test? Here is an [example](https://github.com/mkorman90/regipy/blob/master/regipy_tests/plugin_tests.py#L733).

**Comment by andreisss** [comment]
Should be ok, first type use this platform, sorry.

**Comment by mkorman90** [comment]
> Should be ok, first type use this platform, sorry.

https://github.com/mkorman90/regipy/actions/runs/3474264892/jobs/5943199839
Can you please fix the test? Then we can merge

**Review by andreisss — COMMENTED** [review]
Cheanged should be fine

**Comment by andreisss** [comment]
image
localhost test

**Review by mkorman90 — APPROVED** [review]
Looks great! Thanks

**Pull request merged**
